# # https://taskfile.dev
# When doing interpolation of variables, Task will look for the below. They are listed below in order of importance (i.e. most important first):

# Variables declared in the task definition
# Variables given while calling a task from another (See Calling another task above)
# Variables of the included Taskfile (when the task is included)
# Variables of the inclusion of the Taskfile (when the task is included)
# Global variables (those declared in the vars: option in the Taskfile)
# Environment variables

version: '3'

# Vars get pulled from included taskfiles
includes:
  greet.tasks:
    taskfile: greet.tasks.yaml

  greet.tasks.override:
    taskfile: greet.tasks.yaml
    vars:
      # but we can override them like this:
      INCLUSION_GREETING: Hi

vars:
  GREETING: Here we play with variables

dotenv: ['.env']

tasks:
  default:
    desc: Here we use a global variable
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  greet-env:
    desc: global variable and enviroment variable do not fight, we can even use them together (not recommended though, it quickly gets complex)
    cmds:
      - echo "{{.GREETING}}"
      - echo $GREETING
    env:
      GREETING: Hello, dear user! Here is the environment variable, it doesn't override the global task variable

  greet-var:
    desc: local variable overrides the global one
    cmds:
      - echo "{{.GREETING}}"
    vars:
      GREETING: Hello, dear user! Note that the local greeting overrides the global one


  greet-call-task:
    desc: here we call other tasks not overriding any variables
    cmds:
      - task greet-env
      - task greet-var

  greet-call-task-override:
    desc: here we call a task overriding its variable
    cmds:
      - task greet-var
    vars:
      GREETING: This will be overriden by the variable from task greet-var
  

  # Try calling this task like this: REQUEST=Kazakhstan task grep-dataset-env
  greet-dot-env:
    desc: Getting environment variables from .env file
    cmds:
      - echo $ENV_GREETING $FROM_WHERE

  # Try calling this task like this: REQUEST=Kyrgyzstan task grep-dataset-japan
  greet-dot-env-override:
    desc: Getting environment variables from .env file. A variable from task definition overrides the one from .env file
    cmds:
      - echo $ENV_GREETING $FROM_WHERE
    env:
      FROM_WHERE: from_task 
