# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run-server:
    desc: fire it up!
    cmds:
      - python flask_app/run.py
