# https://taskfile.dev

version: '3'

vars:
  GREETING: To test the app, run-server, then test-web-app. Don't forget to stop the server afterwards

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run-server:
    desc: fire it up!
    cmds:
      - python flask_app/run.py

  test-web-app:
    desc: _
    cmds:
      - pytest tests/test_flask_based_todo_app.pys

  build-docker:
    desc: _
    cmds:
     - docker build -t flask-todo-app .

  
