# https://taskfile.dev

version: '3'

includes:
  conda: taskfiles/conda-venv.tasks.yaml
  py-venv: taskfiles/python-venv.tasks.yaml

vars:
  GREETING: To test the app, run-server, then test-web-app. Don't forget to stop the server afterwards

tasks:
  default:
    desc: List all tasks
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  resolve-deps:
    desc: Install Docker, Pytest and Requests to build app container and run tests
    cmds:
      - task install-docker
      - python -m pip install --upgrade pip
      - pip install pytest requests

  run-server:
    desc: fire it up!
    cmds:
      - python flask_app/run.py

  test-web-app:
    desc: simple test if the app is up and running
    cmds:
      - pytest tests/test_flask_based_todo_app.py

  test-web-app-cypress:
    desc: full-blown cypress webapp test
    cmds:
      - docker build -f cypress.Dockerfile -t cypress-web-test . 
      - docker run -i cypress-web-test


  install-docker:
    desc: install Docker engine
    cmds:
     - task -t taskfiles/setup.os.docker.yaml install-docker

  build-docker:
    desc: _
    cmds:
     - docker build -t flask-todo-app .

  run-docker:
    desc: _
    cmds:
      - docker run -d -p 127.0.0.1:5000:5000 --name flask-todo flask-todo-app

  test-docker:
    desc: Test if container builds and server an app
    cmds:
      - task: build-docker
      - task: run-docker
      - sleep 10
      - task: test-web-app
      - task: test-web-app-cypress
      - task: clean-up-docker

  remove-docker-container:
    desc: _
    cmds:
      - docker stop flask-todo
      - docker container rm flask-todo  
  
  remove-docker-image:
    desc: _
    cmds:
      - docker image rm -f flask-todo-app
      
  clean-up-docker:
    desc: remove docker container and image, for instance after the test
    cmds:
     - task remove-docker-container
     - task remove-docker-image

  
  
