# to create a Taskfile.yaml in a dircetory, run task -i or task --init
# https://taskfile.dev

version: '3'

vars:
  GREETING: 'By default the task runs in the same dircetory where the Taskfile is located, but you can write a custom dircetory for any particular task to run in'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  new-text-file:
    desc: make a new text file inside a new directory. note that the subdirectory gets created if it doesn't yet exist
    dir: temp 
    cmds:
      - echo "That's how task directories work" > thats_how.txt

  read-text:
    desc: read the text file from a subdirectory. if it doesn't exist the task will fail to run
    dir: temp
    cmds:
      - cat thats_how.txt 

  cleanup:
    desc: remove a subdirectory so you can start from scratch. if it doesn't exist the task will fail to run
    cmds:
      - rm -r temp
