# # https://taskfile.dev

version: '3'

includes:
  from-another-file:
    taskfile: greet.tasks.yaml
  from-subdir: ./greet_dir
  # an optional include doesn't throw an error if the included file or directory is not found
  from-nonexisting-file:
    taskfile: taskfile.thats.not.there.yaml
    # comment out the next line to see what will happen when you'll try to call any task
    optional: true

vars:
  GREETING: Here we include an external taskfile

tasks:
  default:
    desc: See, there's only one default task in this file. But you can call 'from-another-file:simple_greet' task
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true
