# # https://taskfile.dev
# When doing interpolation of variables, Task will look for the below. They are listed below in order of importance (i.e. most important first):

# Variables declared in the task definition
# Variables given while calling a task from another (See Calling another task above)
# Variables of the included Taskfile (when the task is included)
# Variables of the inclusion of the Taskfile (when the task is included)
# Global variables (those declared in the vars: option in the Taskfile)
# Environment variables

version: '3'

# Vars get pulled from included taskfiles
includes:
  grep-dataset-product:
    taskfile: grep-dataset.tasks.yaml

  grep-dataset-meat:
    taskfile: grep-dataset.tasks.yaml
    vars:
      # but we can override them like this:
      REGION: Europe

vars:
  GREETING: Here we play with variables

dotenv: ['.env']

tasks:
  default:
    cmds:
      # here we use a global variable, declared in line 16 of this file
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  fetch-dataset:
    desc: download an example dataset
    cmds:
      - wget https://eforexcel.com/wp/wp-content/uploads/2017/07/10000-Sales-Records.zip
      - unzip 10000-Sales-Records.zip

  # Environment variables from .env file
  # Try calling this task like this: REQUEST=Kazakhstan task grep-dataset-env
  grep-dataset-env:
    cmds:
      - cat $DATASET_PATH | grep $REQUEST

  # Environment variables from .env file and in task definition
  # Try calling this task like this: REQUEST=Kyrgyzstan task grep-dataset-japan
  grep-dataset-japan:
    cmds:
      - cat $DATASET_PATH | grep $REQUEST
    env:
      REQUEST: Asia,Japan  
