# https://taskfile.dev

version: '3'

vars:
  GREETING: Dependencies allow easily run tasks in parallel, and that's their main point

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true


