# to create a Taskfile.yaml in a dircetory, run task -i or task --init
# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  fetch-dataset:
    desc: download an example dataset
    cmds:
      - wget https://eforexcel.com/wp/wp-content/uploads/2017/07/10000-Sales-Records.zip
      - unzip 10000-Sales-Records.zip
