name: test-docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Task
        uses: arduino/setup-task@v1

      - run: 'task install-docker'
        name: 'Install Docker'

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

       - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - run: 'task test-docker'
        name: 'Test app in docker container'
